version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333", "6334:6334"]
    volumes: ["./qdrant_data:/qdrant/storage"]
    container_name: qdrant_db

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: palm_mind_db
    ports: ["5432:5432"]
    volumes: ["./postgres_data:/var/lib/postgresql/data"]
    container_name: postgres_db

  redis:
    image: redis:7
    ports: ["6379:6379"]
    container_name: redis_cache